var extraData = {
   {"address":0, "name":"AIN#(0:47)", "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["AIN", "CORE"], "streamable":true, "displayname":["Analog In #"], "description":"Returns the voltage of the specified analog input."},
   {"address":96, "name": "MUX80_X3_AIN#(0:13)", "altnames": ["MUX_X3_AIN#(0:13)", "AIN#(48:61)"], "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["MUX80", "AIN"], "description": "Returns the voltage of the specified multiplexed (with Mux80) analog input."},
   {"address":124, "name": "MUX80_X3_DAC#(0:1)", "altnames": ["MUX_X3_DAC#(0:1)", "AIN#(62:63)"], "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["MUX80", "AIN"], "description": "Returns the voltage of the specified multiplexed (with Mux80) analog input."},
   {"address":128, "name": "MUX80_X3_FIO0#(0:7)", "altnames": ["MUX_X3_FIO0#(0:7)", "AIN#(64:71)"], "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["MUX80", "AIN"], "description": "Returns the voltage of the specified multiplexed (with Mux80) analog input."},
   {"address":144, "name": "MUX80_X4_AIN#(0:13)", "altnames": ["MUX_X4_AIN#(0:13)", "AIN#(72:85)"], "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["MUX80", "AIN"], "description": "Returns the voltage of the specified multiplexed (with Mux80) analog input."},
   {"address":172, "name": "MUX80_X4_DAC#(0:1)", "altnames": ["MUX_X4_DAC#(0:1)", "AIN#(86:87)"], "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["MUX80", "AIN"], "description": "Returns the voltage of the specified multiplexed (with Mux80) analog input."},
   {"address":176, "name": "MUX80_X4_FIO0#(0:7)", "altnames": ["MUX_X4_FIO0#(0:7)", "AIN#(88:95)"], "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["MUX80", "AIN"], "description": "Returns the voltage of the specified multiplexed (with Mux80) analog input."},
   {"address":192, "name": "MUX80_X5_AIN#(0:13)", "altnames": ["MUX_X5_AIN#(0:13)", "AIN#(96:109)"], "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["MUX80", "AIN"], "description": "Returns the voltage of the specified multiplexed (with Mux80) analog input."},
   {"address":220, "name": "MUX80_X5_DAC#(0:1)", "altnames": ["MUX_X5_DAC#(0:1)", "AIN#(110:111)"], "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["MUX80", "AIN"], "description": "Returns the voltage of the specified multiplexed (with Mux80) analog input."},
   {"address":224, "name": "MUX80_X5_FIO0#(0:7)", "altnames": ["MUX_X5_FIO0#(0:7)", "AIN#(112:119)"], "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["MUX80", "AIN"], "description": "Returns the voltage of the specified multiplexed (with Mux80) analog input."},
   {"address":240, "name": "MUX80_X2_AIN#(0:13)", "altnames": ["MUX_X2_AIN#(0:13)", "AIN#(120:127)"], "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["MUX80", "AIN"], "description": "Returns the voltage of the specified multiplexed (with Mux80) analog input."},
   {"address":256, "name":"AIN#(128:254)", "type":"FLOAT32", "devices":["T7"], "readwrite":"R", "tags":["AIN"], "streamable":true, "displayname":["Analog In #"], "description":"These are undefined analog inputs here as future space holders."},
};