

var eventList = {
	PERFORMING_LIST_ALL_EXTENDED: 'PERFORMING_LIST_ALL_EXTENDED',
	FINISHED_LIST_ALL_EXTENDED: 'FINISHED_LIST_ALL_EXTENDED',
	PERFORMING_LIST_ALL: 'PERFORMING_LIST_ALL',
	FINISHED_LIST_ALL: 'FINISHED_LIST_ALL',
	LIST_ALL_EXTENDED_ERROR: 'LIST_ALL_EXTENDED_ERROR',
	DISCOVERED_DEVICE: 'DISCOVERED_DEVICE',
	VERIFYING_DEVICE_CONNECTION: 'VERIFYING_DEVICE_CONNECTION',
	VERIFIED_DEVICE_CONNECTION: 'VERIFIED_DEVICE_CONNECTION',
	FAILED_DEVICE_CONNECTION_VERIFICATION: 'FAILED_DEVICE_CONNECTION_VERIFICATION',
	COLLECTING_REMAINING_DEVICE_INFO: 'FAILED_TO_OPEN_FOUND_DEVICE',
	CLOSING_FOUND_DEVICE: 'CLOSING_FOUND_DEVICE',
	COLLECTING_DATA_FROM_CONNECTED_DEVICE: 'COLLECTING_DATA_FROM_CONNECTED_DEVICE',
	COMBINING_SCAN_RESULTS: 'COMBINING_SCAN_RESULTS',
};
exports.eventList = eventList;