name: Unit Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        node-version: [12.16.3]
        platform: [ubuntu-16.04]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Download ljm
        uses: wei/wget@v1
        with:
          args: -O labjack_ljm_software.tar.gz https://labjack.com/sites/default/files/software/labjack_ljm_software_2019_07_16_x86_64.tar.gz
      - name: Install ljm
        run: tar xfz labjack_ljm_software.tar.gz && cd ./labjack_ljm_software_2019_07_16_x86_64 && sudo ./labjack_ljm_installer.run
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #      - run: npm ci # doesn't work with node8
      - run: npm install --global node-gyp@latest
      - run: npm install
      - run: npm run setup_ci
      - name: Fix lerna mess
        run: node ./scripts/fix_lerna_backup.js
