name: Electron build


on: workflow_dispatch
#on:
#  push: # pull_request:
#    branches: [ electron ] # master

jobs:
  build:

    strategy:
      matrix:
        node-version: [12.16.3]
        platform: [macos-latest]
        #platform: [ubuntu-18.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
#      - name: Download ljm
#        uses: wei/wget@v1
#        with:
#          args: -O labjack_ljm_software.tar.gz https://labjack.com/sites/default/files/software/labjack_ljm_software_2019_07_16_x86_64.tar.gz
#      - name: Install ljm
#        run: tar xfz labjack_ljm_software.tar.gz && cd ./labjack_ljm_software_2019_07_16_x86_64 && sudo ./labjack_ljm_installer.run
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install the Apple certificate and provisioning profile
        env:
          CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
          CERTIFICATE_P12_PASSWORD: ${{ secrets.CERTIFICATE_P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        run: |
          # import certificate and provisioning profile from secrets
          echo -n "$CERTIFICATE_P12" | base64 --decode --output $CERTIFICATE_PATH
          # echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

        run: |
          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        run: |
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$CERTIFICATE_P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

        run: |
          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      #- run: npm ci # doesn't work with node8
      - run: npm install
      - run: npm run setup_ci
      #- name: Fix lerna mess
        #run: node ./scripts/fix_lerna_backup.js
      - run: npm run build
        env:
          BUILD_DIR: ${{ github.workspace }}/build
          USE_HARD_LINKS: "false"
      - run: ls ${{ github.workspace }}/build/output/dist

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/build/output/dist/*



